.catalog:
  name:  demo-php-app # Name of the versioned template of the Catalog Entry
  version:  black # Version of the versioned template of the Catalog Entry
  description: sample demo php app # Description of the versioned template of the Catalog Entry
  uuid: 0750d868-5e88-4eee-bd15-1e8cca0125ba # Unique identifier to be used for upgrades. Please see note.
  minimum_rancher_version: 1.4.1# The minimum version of Rancher that supports the template
  questions: #Used to request user input for configuration options
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should  demo-php-app listen on?"
    default: 80
    required: true
demo-php-app-primary:
  metadata:
