.catalog:
  name:  demo-php-app # Name of the versioned template of the Catalog Entry
  version:  red # Version of the versioned template of the Catalog Entry
  description: sample demo php app # Description of the versioned template of the Catalog Entry
  questions: #Used to request user input for configuration options
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should  demo-php-app listen on?"
    default: 80
    required: true
  output: "${HOSTNAME}:${PORT}"
  url: "http://${HOSTNAME}:${PORT}"
demo-php-app-primary:
  metadata:
